name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-ros:
    strategy:
      fail-fast: false
      matrix:
        image: ["rostooling/setup-ros-docker:ubuntu-bionic-ros-dashing-ros-base-latest"]
        ros-version: [dashing]
        include:
          - image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-testing-latest
            ros-version: foxy
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Fix Bugs in ros-tooling/action-ros-ci
      run: sudo chown -R rosbuild:rosbuild "$HOME" .
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.17
      with:
        package-name: |
          serial_driver
          udp_driver
        source-ros-binary-installation: ${{ matrix.ros-version }}
        vcs-repo-file-url: ""
    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
